const P=window.PROFILE_DATA;
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function renderLinks(){document.getElementById('socialLinks').innerHTML=P.links.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.label)}</a>`).join('')}
function renderResearch(){document.getElementById('researchGrid').innerHTML=P.researchAreas.map(x=>`<article class="research-card"><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}
function renderSelected(){document.getElementById('selectedGrid').innerHTML=P.selectedWorks.map(x=>`<article class="work-card"><span class="tag">${esc(x.label)}</span><h3>${esc(x.title)}</h3><p>${esc(x.venue)} · ${esc(x.year)}</p>${x.link?`<a href="${esc(x.link)}" target="_blank" rel="noopener">View publication ↗</a>`:`<span class="note">Publication record</span>`}</article>`).join('')}
function renderTimeline(id,items){document.getElementById(id).innerHTML=items.map(x=>`<div class="timeline-item"><div class="timeline-period">${esc(x.period)}</div><div><h3>${esc(x.title||x.degree)}</h3><h4>${esc(x.org)}</h4><p>${esc(x.text||x.detail||'')}</p></div></div>`).join('')}
function renderService(){document.getElementById('serviceGrid').innerHTML=Object.entries(P.service).map(([title,items])=>`<section class="service-card"><h3>${esc(title)}</h3><ul class="clean-list">${items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul></section>`).join('')}
function renderChips(id,items){document.getElementById(id).innerHTML=items.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}
function renderPatents(){document.getElementById('patentGrid').innerHTML=P.patentHighlights.map(x=>`<article class="patent-card"><h3>${esc(x.title)}</h3><div class="status">${esc(x.status)}</div><p>${esc(x.text)}</p></article>`).join('')}
const pubList=document.getElementById('pubList'),pubSearch=document.getElementById('pubSearch'),pubType=document.getElementById('pubType'),pubYear=document.getElementById('pubYear');
function authorMarkup(s){return esc(s).replace(/Raffaele Mineo|R\. Mineo/g,'<strong>Raffaele Mineo</strong>')}
function renderPubs(){const q=pubSearch.value.trim().toLowerCase(),typ=pubType.value,yr=pubYear.value;const rows=P.publications.filter(p=>{const hay=[p.title,p.authors,p.venue,p.acronym,p.type,p.year].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!typ||p.type===typ)&&(!yr||String(p.year||'')===yr)});document.getElementById('pubCount').textContent=`${rows.length} item${rows.length===1?'':'s'}`;pubList.innerHTML=rows.map(p=>`<article class="pub"><div class="pub-year">${p.year||'—'}</div><div><div class="pub-title">${esc(p.title)}${p.jointFirst?'<span class="pub-badge">joint first author</span>':''}</div><div class="pub-authors">${authorMarkup(p.authors||'')}</div><div class="pub-meta">${esc(p.acronym||p.venue)}${p.acronym&&p.venue&&p.acronym!==p.venue?' · '+esc(p.venue):''} · ${esc(p.type)}</div></div>${p.link?`<a class="pub-link" href="${esc(p.link)}" target="_blank" rel="noopener">Open ↗</a>`:''}</article>`).join('')}
function initPubFilters(){const types=[...new Set(P.publications.map(p=>p.type).filter(Boolean))].sort();pubType.innerHTML='<option value="">All output types</option>'+types.map(x=>`<option>${esc(x)}</option>`).join('');const years=[...new Set(P.publications.map(p=>p.year).filter(Boolean))].sort((a,b)=>b-a);pubYear.innerHTML='<option value="">All years</option>'+years.map(x=>`<option>${x}</option>`).join('');[pubSearch,pubType,pubYear].forEach(el=>el.addEventListener('input',renderPubs));[pubType,pubYear].forEach(el=>el.addEventListener('change',renderPubs))}
function renderExtended(){document.getElementById('teachingList').innerHTML=P.teaching.map(x=>`<li>${esc(x)}</li>`).join('');document.getElementById('credentialsList').innerHTML=P.credentials.map(x=>`<li>${esc(x)}</li>`).join('');document.getElementById('languagesList').innerHTML=P.languages.map(x=>`<li>${esc(x)}</li>`).join('');document.getElementById('technicalList').innerHTML=Object.entries(P.technical).map(([k,v])=>`<p><strong>${esc(k)}:</strong> ${esc(v)}</p>`).join('')}
function boot(){setText('heroName',P.name);setText('heroRole',P.role);setText('heroAffiliation',P.affiliation);setText('heroCopy',P.researchStatement);setText('location',P.location);setText('emailText',P.email);document.getElementById('emailLink').href='mailto:'+(P.emailHref||P.email.replace('[at]','@'));renderLinks();renderResearch();renderSelected();renderTimeline('experienceTimeline',P.experience);renderTimeline('educationTimeline',P.education);renderService();renderChips('membershipChips',P.memberships);renderChips('collabChips',P.collaborations);renderPatents();initPubFilters();renderPubs();renderExtended();document.getElementById('yearNow').textContent=new Date().getFullYear();document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('navLinks').classList.toggle('open'));document.querySelectorAll('#navLinks a').forEach(a=>a.addEventListener('click',()=>document.getElementById('navLinks').classList.remove('open')))}
boot();
